#!/bin/bash

for file in dotfiles/*; do
  name=`basename $file`
  if [ -e $HOME/.$name ] ; then
    echo "# ~/.$name exists, install manually with"
    echo "cp -a $file $HOME/.$name"
  else
    cp -a $file $HOME/.$name
  fi
done

for script in local/bin/*; do
  name=`basename $script`
  if [ -e $HOME/.local/bin/$name ] ; then
    echo "# ~/.local/bin/$name exists, not updating"
  else
    cp -a $script $HOME/.local/bin/
  fi
done
